### PR TITLE
Remove TypeKit and Google Analytics

### PR DESCRIPTION
**Pull request by troyswanson**
Howdy @j1wu!

Not sure if you knew this, but you are sending traffic data to my Google Analytics account! It's not a big deal, but I thought you might want to know about it so that you can track traffic on your own account.

In addition, this TypeKit account will not work because it's locked down to using my domain

Glad you're enjoying the theme, though, and thanks for the linkback on your README :smile:

### CODE REVIEW

**Comment by troyswanson** [comment]
Also, just a quick note: you should probably include the `_site` directory in your `.gitignore` file. GitHub Pages automatically generates that folder and serves it, so you don't need to include it in your source.

**Comment by j1wu** [comment]
This is embracing...Mr. Troy so sorry about the inconvenience.

**Comment by troyswanson** [comment]
No worries! :heart: I'm glad you liked my site enough to use the theme :smiley:

**Comment by j1wu** [comment]
Thank you so much, and yes, that's the best :+1: and you're the best !

**Pull request merged**
